framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
            - fr
    session:
        enabled: true

# App\LocaleListener configuration
services:
    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_subscriber }