controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
manage_routes:
    resource: ../src/Controller/Manage/
    type: attribute
    prefix: /{_locale}/manage
    requirements:
        _locale: '%app_locales%'
#admin_dashboard:
#    path: /{appId}/admin
#    controller: App\Controller\Admin\DashboardController::index
#    requirements:
#        appId: '\d+'  # ou une autre expression régulière correspondant à vos IDs d'application
#    defaults:
#        _admin: true